blog/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r"^$", views.PostListView.as_view(), name="list"),
    url(r"^(?P<slug>[\w-]+)/$", views.PostDetailView.as_view(), name="detail"),
)

microblog/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from . import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'microblog.views.home', name='home'),
    # url(r'^microblog/', include('microblog.foo.urls')),
    url(r"^$", views.HomepageView.as_view(), name="home"),
    url(r"^blog/", include("blog.urls", namespace="blog")),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    (r'^static/(.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT
    }),
)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class PostManager(models.Manager):
    def live(self):
        return self.model.objects.filter(published=True)


class Post(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, default='')
    content = models.TextField()
    published = models.BooleanField(default=True)
    author = models.ForeignKey(User, related_name="posts")
    objects = PostManager()

    class Meta:
        ordering = ["-created_at", "title"]

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ("blog:detail", (), {"slug": self.slug})

blog/views.py
from django.views.generic import ListView, DetailView

from .models import Post


class PublishedPostsMixin(object):
    def get_queryset(self):
        return self.model.objects.live()


class PostListView(PublishedPostsMixin, ListView):
    model = Post


class PostDetailView(PublishedPostsMixin, DetailView):
    model = Post

microblog/views.py
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = "index.html"

blog/templates/blog/post_detail.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_title %}{{ post.title }} | {% endblock %}

{% block page_content %}
<h2>{{ post.title }}</h2>
{{ post.content|linebreaks }}
<p>{{ post.updated_at }}</p>
<p><a href="{% url 'blog:list' %}">&larr; Blog list</a></p>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "_layouts/base.html" %}

{% block page_title %}Blog posts | {% endblock %}

{% block page_content %}
<h2>Blog Posts</h2>

<ul>
    {% for post in post_list %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% empty %}
    <li>Sorry, no posts yet. Check back soon!</li>
    {% endfor %}
</ul>
{% endblock %}

microblog/templates/_layouts/base.html
<!doctype html>
<html>
    <head>
        <title>{% block page_title %}{% endblock %}Microblog</title>
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css">
    </head>
    <body>
        <div class="container">
            <h1>Welcome to my site!</h1>
            {% block page_content %}{% endblock %}
        </div>
    </body>
</html>

microblog/templates/index.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_content %}
<div class="row-fluid">
    <a href="{% url 'blog:list' %}" class="btn">Read my blog</a>
</div>
{% endblock %}